// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// SubmitChallengeJSONBody defines parameters for SubmitChallenge.
type SubmitChallengeJSONBody struct {
	Results []struct {
		Message *string `json:"message,omitempty"`

		// ObjectiveKey Validation key (e.g. pod-ready-check)
		ObjectiveKey string `json:"objectiveKey"`
		Passed       bool   `json:"passed"`
	} `json:"results"`
}

// TrackSetupJSONBody defines parameters for TrackSetup.
type TrackSetupJSONBody struct {
	Arch       string `json:"arch"`
	CliVersion string `json:"cliVersion"`
	Os         string `json:"os"`
}

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody struct {
	Arch       string `json:"arch"`
	CliVersion string `json:"cliVersion"`
	Os         string `json:"os"`
}

// SubmitChallengeJSONRequestBody defines body for SubmitChallenge for application/json ContentType.
type SubmitChallengeJSONRequestBody SubmitChallengeJSONBody

// TrackSetupJSONRequestBody defines body for TrackSetup for application/json ContentType.
type TrackSetupJSONRequestBody TrackSetupJSONBody

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetChallenge request
	GetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResetChallenge request
	ResetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartChallenge request
	StartChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallengeStatus request
	GetChallengeStatus(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitChallengeWithBody request with any body
	SubmitChallengeWithBody(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubmitChallenge(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TrackSetupWithBody request with any body
	TrackSetupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TrackSetup(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser request
	GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginUserWithBody request with any body
	LoginUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LoginUser(ctx context.Context, body LoginUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResetChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallengeStatus(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeStatusRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitChallengeWithBody(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitChallengeRequestWithBody(c.Server, slug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitChallenge(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitChallengeRequest(c.Server, slug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackSetupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackSetupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackSetup(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackSetupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginUser(ctx context.Context, body LoginUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetChallengeRequest generates requests for GetChallenge
func NewGetChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/challenge/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResetChallengeRequest generates requests for ResetChallenge
func NewResetChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/challenge/%s/reset", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartChallengeRequest generates requests for StartChallenge
func NewStartChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/challenge/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChallengeStatusRequest generates requests for GetChallengeStatus
func NewGetChallengeStatusRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/challenge/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitChallengeRequest calls the generic SubmitChallenge builder with application/json body
func NewSubmitChallengeRequest(server string, slug string, body SubmitChallengeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitChallengeRequestWithBody(server, slug, "application/json", bodyReader)
}

// NewSubmitChallengeRequestWithBody generates requests for SubmitChallenge with any type of body
func NewSubmitChallengeRequestWithBody(server string, slug string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/challenge/%s/submit", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTrackSetupRequest calls the generic TrackSetup builder with application/json body
func NewTrackSetupRequest(server string, body TrackSetupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTrackSetupRequestWithBody(server, "application/json", bodyReader)
}

// NewTrackSetupRequestWithBody generates requests for TrackSetup with any type of body
func NewTrackSetupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/track/setup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUserRequest generates requests for GetUser
func NewGetUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLoginUserRequest calls the generic LoginUser builder with application/json body
func NewLoginUserRequest(server string, body LoginUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginUserRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginUserRequestWithBody generates requests for LoginUser with any type of body
func NewLoginUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetChallengeWithResponse request
	GetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeResponse, error)

	// ResetChallengeWithResponse request
	ResetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*ResetChallengeResponse, error)

	// StartChallengeWithResponse request
	StartChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*StartChallengeResponse, error)

	// GetChallengeStatusWithResponse request
	GetChallengeStatusWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeStatusResponse, error)

	// SubmitChallengeWithBodyWithResponse request with any body
	SubmitChallengeWithBodyWithResponse(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error)

	SubmitChallengeWithResponse(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error)

	// TrackSetupWithBodyWithResponse request with any body
	TrackSetupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error)

	TrackSetupWithResponse(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error)

	// GetUserWithResponse request
	GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// LoginUserWithBodyWithResponse request with any body
	LoginUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginUserResponse, error)

	LoginUserWithResponse(ctx context.Context, body LoginUserJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginUserResponse, error)
}

type GetChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Description      string                    `json:"description"`
		Difficulty       GetChallenge200Difficulty `json:"difficulty"`
		Id               int                       `json:"id"`
		InitialSituation string                    `json:"initial_situation"`
		Objective        string                    `json:"objective"`
		Slug             string                    `json:"slug"`
		Theme            string                    `json:"theme"`
		Title            string                    `json:"title"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type GetChallenge200Difficulty string

// Status returns HTTPResponse.Status
func (r GetChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResetChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message string `json:"message"`
		Success bool   `json:"success"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ResetChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResetChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message *string `json:"message,omitempty"`

		// StartedAt ISO 8601 date string
		StartedAt string                  `json:"startedAt"`
		Status    StartChallenge200Status `json:"status"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type StartChallenge200Status string

// Status returns HTTPResponse.Status
func (r StartChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// CompletedAt ISO 8601 date string
		CompletedAt *string `json:"completedAt,omitempty"`

		// StartedAt ISO 8601 date string
		StartedAt *string                     `json:"startedAt,omitempty"`
		Status    GetChallengeStatus200Status `json:"status"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type GetChallengeStatus200Status string

// Status returns HTTPResponse.Status
func (r GetChallengeStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SubmitChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstChallenge *bool                     `json:"firstChallenge,omitempty"`
		Rank           string                    `json:"rank"`
		RankUp         *bool                     `json:"rankUp,omitempty"`
		Success        SubmitChallenge200Success `json:"success"`
		TotalXp        float32                   `json:"totalXp"`
		XpAwarded      float32                   `json:"xpAwarded"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type SubmitChallenge200Success bool

// Status returns HTTPResponse.Status
func (r SubmitChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TrackSetupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstTime bool `json:"firstTime"`
		Success   bool `json:"success"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r TrackSetupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TrackSetupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstName string  `json:"firstName"`
		LastName  *string `json:"lastName"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LoginUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstLogin bool    `json:"firstLogin"`
		FirstName  string  `json:"firstName"`
		LastName   *string `json:"lastName"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r LoginUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetChallengeWithResponse request returning *GetChallengeResponse
func (c *ClientWithResponses) GetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeResponse, error) {
	rsp, err := c.GetChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeResponse(rsp)
}

// ResetChallengeWithResponse request returning *ResetChallengeResponse
func (c *ClientWithResponses) ResetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*ResetChallengeResponse, error) {
	rsp, err := c.ResetChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResetChallengeResponse(rsp)
}

// StartChallengeWithResponse request returning *StartChallengeResponse
func (c *ClientWithResponses) StartChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*StartChallengeResponse, error) {
	rsp, err := c.StartChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartChallengeResponse(rsp)
}

// GetChallengeStatusWithResponse request returning *GetChallengeStatusResponse
func (c *ClientWithResponses) GetChallengeStatusWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeStatusResponse, error) {
	rsp, err := c.GetChallengeStatus(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeStatusResponse(rsp)
}

// SubmitChallengeWithBodyWithResponse request with arbitrary body returning *SubmitChallengeResponse
func (c *ClientWithResponses) SubmitChallengeWithBodyWithResponse(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error) {
	rsp, err := c.SubmitChallengeWithBody(ctx, slug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitChallengeResponse(rsp)
}

func (c *ClientWithResponses) SubmitChallengeWithResponse(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error) {
	rsp, err := c.SubmitChallenge(ctx, slug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitChallengeResponse(rsp)
}

// TrackSetupWithBodyWithResponse request with arbitrary body returning *TrackSetupResponse
func (c *ClientWithResponses) TrackSetupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error) {
	rsp, err := c.TrackSetupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackSetupResponse(rsp)
}

func (c *ClientWithResponses) TrackSetupWithResponse(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error) {
	rsp, err := c.TrackSetup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackSetupResponse(rsp)
}

// GetUserWithResponse request returning *GetUserResponse
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// LoginUserWithBodyWithResponse request with arbitrary body returning *LoginUserResponse
func (c *ClientWithResponses) LoginUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginUserResponse, error) {
	rsp, err := c.LoginUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginUserResponse(rsp)
}

func (c *ClientWithResponses) LoginUserWithResponse(ctx context.Context, body LoginUserJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginUserResponse, error) {
	rsp, err := c.LoginUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginUserResponse(rsp)
}

// ParseGetChallengeResponse parses an HTTP response from a GetChallengeWithResponse call
func ParseGetChallengeResponse(rsp *http.Response) (*GetChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Description      string                    `json:"description"`
			Difficulty       GetChallenge200Difficulty `json:"difficulty"`
			Id               int                       `json:"id"`
			InitialSituation string                    `json:"initial_situation"`
			Objective        string                    `json:"objective"`
			Slug             string                    `json:"slug"`
			Theme            string                    `json:"theme"`
			Title            string                    `json:"title"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseResetChallengeResponse parses an HTTP response from a ResetChallengeWithResponse call
func ParseResetChallengeResponse(rsp *http.Response) (*ResetChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResetChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message string `json:"message"`
			Success bool   `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStartChallengeResponse parses an HTTP response from a StartChallengeWithResponse call
func ParseStartChallengeResponse(rsp *http.Response) (*StartChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message *string `json:"message,omitempty"`

			// StartedAt ISO 8601 date string
			StartedAt string                  `json:"startedAt"`
			Status    StartChallenge200Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeStatusResponse parses an HTTP response from a GetChallengeStatusWithResponse call
func ParseGetChallengeStatusResponse(rsp *http.Response) (*GetChallengeStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// CompletedAt ISO 8601 date string
			CompletedAt *string `json:"completedAt,omitempty"`

			// StartedAt ISO 8601 date string
			StartedAt *string                     `json:"startedAt,omitempty"`
			Status    GetChallengeStatus200Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSubmitChallengeResponse parses an HTTP response from a SubmitChallengeWithResponse call
func ParseSubmitChallengeResponse(rsp *http.Response) (*SubmitChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstChallenge *bool                     `json:"firstChallenge,omitempty"`
			Rank           string                    `json:"rank"`
			RankUp         *bool                     `json:"rankUp,omitempty"`
			Success        SubmitChallenge200Success `json:"success"`
			TotalXp        float32                   `json:"totalXp"`
			XpAwarded      float32                   `json:"xpAwarded"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTrackSetupResponse parses an HTTP response from a TrackSetupWithResponse call
func ParseTrackSetupResponse(rsp *http.Response) (*TrackSetupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TrackSetupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstTime bool `json:"firstTime"`
			Success   bool `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstName string  `json:"firstName"`
			LastName  *string `json:"lastName"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLoginUserResponse parses an HTTP response from a LoginUserWithResponse call
func ParseLoginUserResponse(rsp *http.Response) (*LoginUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstLogin bool    `json:"firstLogin"`
			FirstName  string  `json:"firstName"`
			LastName   *string `json:"lastName"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
