// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes  = "BearerAuth.Scopes"
	SessionAuthScopes = "SessionAuth.Scopes"
)

// Defines values for ListChallengesParamsDifficulty.
const (
	Easy   ListChallengesParamsDifficulty = "easy"
	Hard   ListChallengesParamsDifficulty = "hard"
	Medium ListChallengesParamsDifficulty = "medium"
)

// ListChallengesParams defines parameters for ListChallenges.
type ListChallengesParams struct {
	Difficulty    *ListChallengesParamsDifficulty `form:"difficulty,omitempty" json:"difficulty,omitempty"`
	Type          *string                         `form:"type,omitempty" json:"type,omitempty"`
	Theme         *string                         `form:"theme,omitempty" json:"theme,omitempty"`
	Search        *string                         `form:"search,omitempty" json:"search,omitempty"`
	ShowCompleted *string                         `form:"showCompleted,omitempty" json:"showCompleted,omitempty"`
}

// ListChallengesParamsDifficulty defines parameters for ListChallenges.
type ListChallengesParamsDifficulty string

// SubmitChallengeJSONBody defines parameters for SubmitChallenge.
type SubmitChallengeJSONBody struct {
	AuditEvents *[]struct {
		Name         *string   `json:"name,omitempty"`
		Namespace    *string   `json:"namespace,omitempty"`
		Resource     string    `json:"resource"`
		ResponseCode *int      `json:"responseCode,omitempty"`
		Subresource  *string   `json:"subresource,omitempty"`
		Timestamp    time.Time `json:"timestamp"`
		UserAgent    *string   `json:"userAgent,omitempty"`
		Verb         string    `json:"verb"`
	} `json:"auditEvents,omitempty"`
	Results []struct {
		Message      *string `json:"message,omitempty"`
		ObjectiveKey string  `json:"objectiveKey"`
		Passed       bool    `json:"passed"`
	} `json:"results"`
}

// TrackCliLoginJSONBody defines parameters for TrackCliLogin.
type TrackCliLoginJSONBody struct {
	Arch       string `json:"arch"`
	CliVersion string `json:"cliVersion"`
	Os         string `json:"os"`
}

// TrackSetupJSONBody defines parameters for TrackSetup.
type TrackSetupJSONBody struct {
	Arch       string `json:"arch"`
	CliVersion string `json:"cliVersion"`
	Os         string `json:"os"`
}

// SubmitChallengeJSONRequestBody defines body for SubmitChallenge for application/json ContentType.
type SubmitChallengeJSONRequestBody SubmitChallengeJSONBody

// TrackCliLoginJSONRequestBody defines body for TrackCliLogin for application/json ContentType.
type TrackCliLoginJSONRequestBody TrackCliLoginJSONBody

// TrackSetupJSONRequestBody defines body for TrackSetup for application/json ContentType.
type TrackSetupJSONRequestBody TrackSetupJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListChallenges request
	ListChallenges(ctx context.Context, params *ListChallengesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallengeMeta request
	GetChallengeMeta(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallenge request
	GetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallengeManifests request
	GetChallengeManifests(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitChallengeWithBody request with any body
	SubmitChallengeWithBody(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubmitChallenge(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallengeYaml request
	GetChallengeYaml(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TrackCliLoginWithBody request with any body
	TrackCliLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TrackCliLogin(ctx context.Context, body TrackCliLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TrackSetupWithBody request with any body
	TrackSetupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TrackSetup(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChallengeStatus request
	GetChallengeStatus(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResetChallenge request
	ResetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartChallenge request
	StartChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserMe request
	GetUserMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListChallenges(ctx context.Context, params *ListChallengesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListChallengesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallengeMeta(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeMetaRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallengeManifests(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeManifestsRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitChallengeWithBody(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitChallengeRequestWithBody(c.Server, slug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitChallenge(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitChallengeRequest(c.Server, slug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallengeYaml(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeYamlRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackCliLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackCliLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackCliLogin(ctx context.Context, body TrackCliLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackCliLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackSetupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackSetupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackSetup(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackSetupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChallengeStatus(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChallengeStatusRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResetChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResetChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartChallenge(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartChallengeRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListChallengesRequest generates requests for ListChallenges
func NewListChallengesRequest(server string, params *ListChallengesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Difficulty != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "difficulty", runtime.ParamLocationQuery, *params.Difficulty); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Theme != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "theme", runtime.ParamLocationQuery, *params.Theme); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Search != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search", runtime.ParamLocationQuery, *params.Search); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ShowCompleted != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "showCompleted", runtime.ParamLocationQuery, *params.ShowCompleted); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChallengeMetaRequest generates requests for GetChallengeMeta
func NewGetChallengeMetaRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges/meta")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChallengeRequest generates requests for GetChallenge
func NewGetChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChallengeManifestsRequest generates requests for GetChallengeManifests
func NewGetChallengeManifestsRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges/%s/manifests", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitChallengeRequest calls the generic SubmitChallenge builder with application/json body
func NewSubmitChallengeRequest(server string, slug string, body SubmitChallengeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitChallengeRequestWithBody(server, slug, "application/json", bodyReader)
}

// NewSubmitChallengeRequestWithBody generates requests for SubmitChallenge with any type of body
func NewSubmitChallengeRequestWithBody(server string, slug string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges/%s/submit", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetChallengeYamlRequest generates requests for GetChallengeYaml
func NewGetChallengeYamlRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/challenges/%s/yaml", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTrackCliLoginRequest calls the generic TrackCliLogin builder with application/json body
func NewTrackCliLoginRequest(server string, body TrackCliLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTrackCliLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewTrackCliLoginRequestWithBody generates requests for TrackCliLogin with any type of body
func NewTrackCliLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/track/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTrackSetupRequest calls the generic TrackSetup builder with application/json body
func NewTrackSetupRequest(server string, body TrackSetupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTrackSetupRequestWithBody(server, "application/json", bodyReader)
}

// NewTrackSetupRequestWithBody generates requests for TrackSetup with any type of body
func NewTrackSetupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/track/setup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetChallengeStatusRequest generates requests for GetChallengeStatus
func NewGetChallengeStatusRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/progress/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResetChallengeRequest generates requests for ResetChallenge
func NewResetChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/progress/%s/reset", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartChallengeRequest generates requests for StartChallenge
func NewStartChallengeRequest(server string, slug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/progress/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserMeRequest generates requests for GetUserMe
func NewGetUserMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/user/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListChallengesWithResponse request
	ListChallengesWithResponse(ctx context.Context, params *ListChallengesParams, reqEditors ...RequestEditorFn) (*ListChallengesResponse, error)

	// GetChallengeMetaWithResponse request
	GetChallengeMetaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetChallengeMetaResponse, error)

	// GetChallengeWithResponse request
	GetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeResponse, error)

	// GetChallengeManifestsWithResponse request
	GetChallengeManifestsWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeManifestsResponse, error)

	// SubmitChallengeWithBodyWithResponse request with any body
	SubmitChallengeWithBodyWithResponse(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error)

	SubmitChallengeWithResponse(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error)

	// GetChallengeYamlWithResponse request
	GetChallengeYamlWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeYamlResponse, error)

	// TrackCliLoginWithBodyWithResponse request with any body
	TrackCliLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackCliLoginResponse, error)

	TrackCliLoginWithResponse(ctx context.Context, body TrackCliLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackCliLoginResponse, error)

	// TrackSetupWithBodyWithResponse request with any body
	TrackSetupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error)

	TrackSetupWithResponse(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error)

	// GetChallengeStatusWithResponse request
	GetChallengeStatusWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeStatusResponse, error)

	// ResetChallengeWithResponse request
	ResetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*ResetChallengeResponse, error)

	// StartChallengeWithResponse request
	StartChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*StartChallengeResponse, error)

	// GetUserMeWithResponse request
	GetUserMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserMeResponse, error)
}

type ListChallengesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Challenges []struct {
			CompletedCount   int                                   `json:"completedCount"`
			Description      string                                `json:"description"`
			Difficulty       ListChallenges200ChallengesDifficulty `json:"difficulty"`
			EstimatedTime    int                                   `json:"estimatedTime"`
			InitialSituation string                                `json:"initialSituation"`
			OfTheWeek        bool                                  `json:"ofTheWeek"`
			Slug             string                                `json:"slug"`
			Theme            string                                `json:"theme"`
			ThemeSlug        string                                `json:"themeSlug"`
			Title            string                                `json:"title"`
			Type             string                                `json:"type"`
			TypeSlug         string                                `json:"typeSlug"`
			UserStatus       *string                               `json:"userStatus"`
		} `json:"challenges"`
		Count int `json:"count"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type ListChallenges200ChallengesDifficulty string

// Status returns HTTPResponse.Status
func (r ListChallengesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListChallengesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeMetaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Difficulties []string `json:"difficulties"`
		Themes       []struct {
			Description string `json:"description"`
			Logo        string `json:"logo"`
			Name        string `json:"name"`
			Slug        string `json:"slug"`
		} `json:"themes"`
		Types []struct {
			Description string `json:"description"`
			Logo        string `json:"logo"`
			Name        string `json:"name"`
			Slug        string `json:"slug"`
		} `json:"types"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetChallengeMetaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeMetaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Challenge *struct {
			Available        bool                               `json:"available"`
			Description      string                             `json:"description"`
			Difficulty       GetChallenge200ChallengeDifficulty `json:"difficulty"`
			EstimatedTime    int                                `json:"estimatedTime"`
			InitialSituation string                             `json:"initialSituation"`
			OfTheWeek        bool                               `json:"ofTheWeek"`
			Slug             string                             `json:"slug"`
			StarterFriendly  bool                               `json:"starterFriendly"`
			Theme            string                             `json:"theme"`
			ThemeSlug        string                             `json:"themeSlug"`
			Title            string                             `json:"title"`
			Type             string                             `json:"type"`
			TypeSlug         string                             `json:"typeSlug"`
		} `json:"challenge"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type GetChallenge200ChallengeDifficulty string

// Status returns HTTPResponse.Status
func (r GetChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeManifestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetChallengeManifestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeManifestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SubmitChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Objectives []struct {
			Category    SubmitChallenge200ObjectivesCategory `json:"category"`
			Description *string                              `json:"description,omitempty"`
			Key         string                               `json:"key"`
			Message     *string                              `json:"message,omitempty"`
			Passed      bool                                 `json:"passed"`
			Title       string                               `json:"title"`
		} `json:"objectives"`
		Success SubmitChallenge200Success `json:"success"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON409 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON422 *struct {
		union json.RawMessage
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type SubmitChallenge200ObjectivesCategory string
type SubmitChallenge200Success bool
type SubmitChallenge4220 struct {
	FailedObjectives []struct {
		Key     string `json:"key"`
		Message string `json:"message"`
		Title   string `json:"title"`
	} `json:"failedObjectives"`
	Objectives []struct {
		Category    SubmitChallenge4220ObjectivesCategory `json:"category"`
		Description *string                               `json:"description,omitempty"`
		Key         string                                `json:"key"`
		Message     *string                               `json:"message,omitempty"`
		Passed      bool                                  `json:"passed"`
		Title       string                                `json:"title"`
	} `json:"objectives"`
	Success SubmitChallenge4220Success `json:"success"`
}
type SubmitChallenge4220ObjectivesCategory string
type SubmitChallenge4220Success bool
type SubmitChallenge4221 struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// Status returns HTTPResponse.Status
func (r SubmitChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeYamlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetChallengeYamlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeYamlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TrackCliLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstLogin bool `json:"firstLogin"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r TrackCliLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TrackCliLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TrackSetupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FirstTime bool `json:"firstTime"`
		Success   bool `json:"success"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r TrackSetupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TrackSetupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChallengeStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		CompletedAt *time.Time                  `json:"completedAt"`
		StartedAt   *time.Time                  `json:"startedAt"`
		Status      GetChallengeStatus200Status `json:"status"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type GetChallengeStatus200Status string

// Status returns HTTPResponse.Status
func (r GetChallengeStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChallengeStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResetChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message string `json:"message"`
		Success bool   `json:"success"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ResetChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResetChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message   *string                 `json:"message,omitempty"`
		StartedAt *time.Time              `json:"startedAt"`
		Status    StartChallenge200Status `json:"status"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON404 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}
type StartChallenge200Status string

// Status returns HTTPResponse.Status
func (r StartChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Email string  `json:"email"`
		Id    string  `json:"id"`
		Image *string `json:"image"`
		Name  string  `json:"name"`
	}
	JSON400 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON401 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
	JSON500 *struct {
		Details *string `json:"details,omitempty"`
		Error   string  `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetUserMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListChallengesWithResponse request returning *ListChallengesResponse
func (c *ClientWithResponses) ListChallengesWithResponse(ctx context.Context, params *ListChallengesParams, reqEditors ...RequestEditorFn) (*ListChallengesResponse, error) {
	rsp, err := c.ListChallenges(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListChallengesResponse(rsp)
}

// GetChallengeMetaWithResponse request returning *GetChallengeMetaResponse
func (c *ClientWithResponses) GetChallengeMetaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetChallengeMetaResponse, error) {
	rsp, err := c.GetChallengeMeta(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeMetaResponse(rsp)
}

// GetChallengeWithResponse request returning *GetChallengeResponse
func (c *ClientWithResponses) GetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeResponse, error) {
	rsp, err := c.GetChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeResponse(rsp)
}

// GetChallengeManifestsWithResponse request returning *GetChallengeManifestsResponse
func (c *ClientWithResponses) GetChallengeManifestsWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeManifestsResponse, error) {
	rsp, err := c.GetChallengeManifests(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeManifestsResponse(rsp)
}

// SubmitChallengeWithBodyWithResponse request with arbitrary body returning *SubmitChallengeResponse
func (c *ClientWithResponses) SubmitChallengeWithBodyWithResponse(ctx context.Context, slug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error) {
	rsp, err := c.SubmitChallengeWithBody(ctx, slug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitChallengeResponse(rsp)
}

func (c *ClientWithResponses) SubmitChallengeWithResponse(ctx context.Context, slug string, body SubmitChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitChallengeResponse, error) {
	rsp, err := c.SubmitChallenge(ctx, slug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitChallengeResponse(rsp)
}

// GetChallengeYamlWithResponse request returning *GetChallengeYamlResponse
func (c *ClientWithResponses) GetChallengeYamlWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeYamlResponse, error) {
	rsp, err := c.GetChallengeYaml(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeYamlResponse(rsp)
}

// TrackCliLoginWithBodyWithResponse request with arbitrary body returning *TrackCliLoginResponse
func (c *ClientWithResponses) TrackCliLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackCliLoginResponse, error) {
	rsp, err := c.TrackCliLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackCliLoginResponse(rsp)
}

func (c *ClientWithResponses) TrackCliLoginWithResponse(ctx context.Context, body TrackCliLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackCliLoginResponse, error) {
	rsp, err := c.TrackCliLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackCliLoginResponse(rsp)
}

// TrackSetupWithBodyWithResponse request with arbitrary body returning *TrackSetupResponse
func (c *ClientWithResponses) TrackSetupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error) {
	rsp, err := c.TrackSetupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackSetupResponse(rsp)
}

func (c *ClientWithResponses) TrackSetupWithResponse(ctx context.Context, body TrackSetupJSONRequestBody, reqEditors ...RequestEditorFn) (*TrackSetupResponse, error) {
	rsp, err := c.TrackSetup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackSetupResponse(rsp)
}

// GetChallengeStatusWithResponse request returning *GetChallengeStatusResponse
func (c *ClientWithResponses) GetChallengeStatusWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*GetChallengeStatusResponse, error) {
	rsp, err := c.GetChallengeStatus(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChallengeStatusResponse(rsp)
}

// ResetChallengeWithResponse request returning *ResetChallengeResponse
func (c *ClientWithResponses) ResetChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*ResetChallengeResponse, error) {
	rsp, err := c.ResetChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResetChallengeResponse(rsp)
}

// StartChallengeWithResponse request returning *StartChallengeResponse
func (c *ClientWithResponses) StartChallengeWithResponse(ctx context.Context, slug string, reqEditors ...RequestEditorFn) (*StartChallengeResponse, error) {
	rsp, err := c.StartChallenge(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartChallengeResponse(rsp)
}

// GetUserMeWithResponse request returning *GetUserMeResponse
func (c *ClientWithResponses) GetUserMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserMeResponse, error) {
	rsp, err := c.GetUserMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserMeResponse(rsp)
}

// ParseListChallengesResponse parses an HTTP response from a ListChallengesWithResponse call
func ParseListChallengesResponse(rsp *http.Response) (*ListChallengesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListChallengesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Challenges []struct {
				CompletedCount   int                                   `json:"completedCount"`
				Description      string                                `json:"description"`
				Difficulty       ListChallenges200ChallengesDifficulty `json:"difficulty"`
				EstimatedTime    int                                   `json:"estimatedTime"`
				InitialSituation string                                `json:"initialSituation"`
				OfTheWeek        bool                                  `json:"ofTheWeek"`
				Slug             string                                `json:"slug"`
				Theme            string                                `json:"theme"`
				ThemeSlug        string                                `json:"themeSlug"`
				Title            string                                `json:"title"`
				Type             string                                `json:"type"`
				TypeSlug         string                                `json:"typeSlug"`
				UserStatus       *string                               `json:"userStatus"`
			} `json:"challenges"`
			Count int `json:"count"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeMetaResponse parses an HTTP response from a GetChallengeMetaWithResponse call
func ParseGetChallengeMetaResponse(rsp *http.Response) (*GetChallengeMetaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeMetaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Difficulties []string `json:"difficulties"`
			Themes       []struct {
				Description string `json:"description"`
				Logo        string `json:"logo"`
				Name        string `json:"name"`
				Slug        string `json:"slug"`
			} `json:"themes"`
			Types []struct {
				Description string `json:"description"`
				Logo        string `json:"logo"`
				Name        string `json:"name"`
				Slug        string `json:"slug"`
			} `json:"types"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeResponse parses an HTTP response from a GetChallengeWithResponse call
func ParseGetChallengeResponse(rsp *http.Response) (*GetChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Challenge *struct {
				Available        bool                               `json:"available"`
				Description      string                             `json:"description"`
				Difficulty       GetChallenge200ChallengeDifficulty `json:"difficulty"`
				EstimatedTime    int                                `json:"estimatedTime"`
				InitialSituation string                             `json:"initialSituation"`
				OfTheWeek        bool                               `json:"ofTheWeek"`
				Slug             string                             `json:"slug"`
				StarterFriendly  bool                               `json:"starterFriendly"`
				Theme            string                             `json:"theme"`
				ThemeSlug        string                             `json:"themeSlug"`
				Title            string                             `json:"title"`
				Type             string                             `json:"type"`
				TypeSlug         string                             `json:"typeSlug"`
			} `json:"challenge"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeManifestsResponse parses an HTTP response from a GetChallengeManifestsWithResponse call
func ParseGetChallengeManifestsResponse(rsp *http.Response) (*GetChallengeManifestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeManifestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSubmitChallengeResponse parses an HTTP response from a SubmitChallengeWithResponse call
func ParseSubmitChallengeResponse(rsp *http.Response) (*SubmitChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Objectives []struct {
				Category    SubmitChallenge200ObjectivesCategory `json:"category"`
				Description *string                              `json:"description,omitempty"`
				Key         string                               `json:"key"`
				Message     *string                              `json:"message,omitempty"`
				Passed      bool                                 `json:"passed"`
				Title       string                               `json:"title"`
			} `json:"objectives"`
			Success SubmitChallenge200Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeYamlResponse parses an HTTP response from a GetChallengeYamlWithResponse call
func ParseGetChallengeYamlResponse(rsp *http.Response) (*GetChallengeYamlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeYamlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTrackCliLoginResponse parses an HTTP response from a TrackCliLoginWithResponse call
func ParseTrackCliLoginResponse(rsp *http.Response) (*TrackCliLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TrackCliLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstLogin bool `json:"firstLogin"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTrackSetupResponse parses an HTTP response from a TrackSetupWithResponse call
func ParseTrackSetupResponse(rsp *http.Response) (*TrackSetupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TrackSetupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FirstTime bool `json:"firstTime"`
			Success   bool `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetChallengeStatusResponse parses an HTTP response from a GetChallengeStatusWithResponse call
func ParseGetChallengeStatusResponse(rsp *http.Response) (*GetChallengeStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChallengeStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CompletedAt *time.Time                  `json:"completedAt"`
			StartedAt   *time.Time                  `json:"startedAt"`
			Status      GetChallengeStatus200Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseResetChallengeResponse parses an HTTP response from a ResetChallengeWithResponse call
func ParseResetChallengeResponse(rsp *http.Response) (*ResetChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResetChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message string `json:"message"`
			Success bool   `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStartChallengeResponse parses an HTTP response from a StartChallengeWithResponse call
func ParseStartChallengeResponse(rsp *http.Response) (*StartChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message   *string                 `json:"message,omitempty"`
			StartedAt *time.Time              `json:"startedAt"`
			Status    StartChallenge200Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUserMeResponse parses an HTTP response from a GetUserMeWithResponse call
func ParseGetUserMeResponse(rsp *http.Response) (*GetUserMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Email string  `json:"email"`
			Id    string  `json:"id"`
			Image *string `json:"image"`
			Name  string  `json:"name"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Details *string `json:"details,omitempty"`
			Error   string  `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
