version: 2
# GoReleaser config for kubeasy-cli
# Docs: https://goreleaser.com/customization/build/

project_name: kubeasy-cli
release:
  github:
    owner: kubeasy-dev
    name: kubeasy-cli
builds:
  - id: kubeasy-cli
    main: ./main.go
    binary: kubeasy
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X 'github.com/kubeasy-dev/kubeasy-cli/pkg/constants.Version={{.Tag}}' -X 'github.com/kubeasy-dev/kubeasy-cli/pkg/constants.LogFilePath=/tmp/kubeasy-cli.log'"
    env:
      - GOPRIVATE=github.com/kubeasy-dev/challenge-operator
archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "build/**"
checksum:
  name_template: "checksums.txt"
blobs:
  - provider: s3
    bucket: kubeasy-cli-binaries
    region: weur
    ids:
      - archive
      - checksums
    endpoint: https://57e2edb42742bf00d9a2526736f3ea36.r2.cloudflarestorage.com
    acl: public-read
snapshot: {}
changelog:
  sort: asc
